parameters:
#    mount_diet.example.class: Mount\DietBundle\Example

services:
#    mount_diet.example:
#        class: %mount_diet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
