<?php

namespace Mount\DietBundle\Entity\Day;

use Doctrine\ORM\EntityRepository;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends EntityRepository
{
}
